### PR TITLE
Fixed: more jobs' name not showing on mobile view (#85zrw8eup)

### LINKED ISSUE #429: More Jobs data on Mobile
## Current behavior

When clicking into the detailed view of a job from the more jobs section, the job configuration component doesn't show the name correctly for the enum or the job.

https://user-images.githubusercontent.com/60128132/230656930-a6cfac0c-f330-4677-ac3d-78f203258f88.MP4

### LINKED ISSUE #430: Job Runtime should be selectable from predefined options
## What is the motivation for adding/enhancing this feature?

Right now, to set runtime, you have to select the date and time from an elaborate picker. sometimes you just want a job to be scheduled without thinking about the time. An option for specific run time should be available as a "custom option" but the first options should be some defaults.

Screenshot 2023-04-07 at 11 17 08 AM

### PR DESCRIPTION
**Pull request by k2maan**
### Related Issues

Closes #429 

### Screenshots of Visual Changes before/after (If There Are Any)
[Screencast from 11-04-23 04:48:02 PM IST.webm](https://user-images.githubusercontent.com/59442907/231145204-86aa6758-05b3-4adc-815c-938514d945e0.webm)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

### CODE REVIEW

File: src/components/JobConfiguration.vue [hunk 1]
```diff
@@ -1,7 +1,7 @@
 <template>
   <section>
     <ion-item lines="none">
-      <h1>{{ title ? $t(title) : '' }}</h1>
+      <h1>{{ currentJob.enumName ? $t(currentJob.enumName) : $t(title) }}</h1>
```
Comment (adityasharma7) [inline src/components/JobConfiguration.vue:4]: We should primarily show title, if not found then show enumName

**Review by adityasharma7 — CHANGES_REQUESTED** [review]

**Review by adityasharma7 — APPROVED** [review]
