### PR TITLE
Fixed: Duplicate batch jobs visible when scheduling a new batch job (#393)

### LINKED ISSUE #393: Duplicate batch jobs visible when scheduling a new batch job
## Current behavior

When scheduling a new batch job, on success all the batch jobs are having duplicate entry.

## Expected behavior

No duplicate job should be displayed

## Steps to reproduce the issue

1. Go to orders page
2. Click on add button on batch section
3. Schedule a job
4. See that all the batch jobs gets duplicated

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by adityasharma7**
### Related Issues

Closes #393

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

### CODE REVIEW

File: src/store/modules/job/actions.ts [hunk 1]
```diff
@@ -529,18 +529,21 @@ const actions: ActionTree<JobState, RootState> = {
...
             'systemJobEnumId_op': 'equals',
-            'statusId': "SERVICE_PENDING",
-            'statusId_op': 'equals'
           },
           orderBy: "runTime ASC"
         })
-        const fetchJobsResponse = jobs[0];
-        if(fetchJobsResponse.status === 200 && !hasError(fetchJobsResponse) && fetchJobsResponse.data?.docs?.length) {
-          commit(types.JOB_CURRENT_UPDATED, fetchJobsResponse.data?.docs[0]);
+        // TODO
```
Comment (adityasharma7) [inline src/store/modules/job/actions.ts:539]:
```suggestion
```
