### PR TITLE
Fixed: search jobs modal showing 'no jobs found' without searching any job (#85zrmar8z)

### LINKED ISSUE #358: Bulk Job scheduling: 'No jobs found' comes when we open the select jobs link
## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by k2maan**
### Related Issues

Closes #358 

### Short Description and Why It's Useful

The select jobs modal showed 'No jobs found' without even searching for a job. Fixed the issue and now the modal shows 'Searched jobs will appear here' if no jobs are searched. 

### Screenshots of Visual Changes before/after (If There Are Any)

Job Manager - HotWax Commerce

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

### CODE REVIEW

File: src/views/SelectJobsModal.vue [hunk 1]
```diff
@@ -12,7 +12,11 @@
   <ion-content>
     <ion-searchbar v-model="queryString" :placeholder="$t('Search jobs')" @keyup.enter="search($event)" />
 
-    <div v-if="jobs.length === 0" class="ion-text-center">
+    <div v-if="!isJobSearched" class="ion-text-center">
+      <p>{{ $t("Searched jobs will appear here") }}</p>
+    </div>    
+
+    <div v-else-if="jobs.length === 0" class="ion-text-center">
```
Comment (disha1202) [inline src/views/SelectJobsModal.vue:19]: Use `queryString` instead of `isJobSearched`

File: src/views/SelectJobsModal.vue [hunk 2]
```diff
@@ -12,7 +12,11 @@
   <ion-content>
     <ion-searchbar v-model="queryString" :placeholder="$t('Search jobs')" @keyup.enter="search($event)" />
 
-    <div v-if="jobs.length === 0" class="ion-text-center">
+    <div v-if="!isJobSearched" class="ion-text-center">
```
Comment (disha1202) [inline src/views/SelectJobsModal.vue:15]: Also we can remove this.

**Review by disha1202 — CHANGES_REQUESTED** [review]

File: src/views/SelectJobsModal.vue (hunk 1 above)
Comment (k2maan) [reply src/views/SelectJobsModal.vue:19]: As queryString is v-modelled with the search bar, even if we type something, without searching (pressing enter) it'll show 'No jobs found' in that case.

Comment (adityasharma7) [reply src/views/SelectJobsModal.vue:19]: Instead of using v-model, we could update the queryString only on enter press. This way we will not need flag variable

**Review by adityasharma7 — CHANGES_REQUESTED** [review]

File: src/views/SelectJobsModal.vue [hunk 3]
```diff
@@ -92,7 +96,9 @@ export default defineComponent({
   methods: {
     async search(event: any) {
       this.queryString = event.target.value.trim();
-      if(this.queryString.length > 0) this.getJobs();
+      if(this.queryString.length > 0) {
```
Comment (adityasharma7) [inline src/views/SelectJobsModal.vue:99]: Why do we need the length check at all?

_"That is, all values are truthy except false, 0, -0, 0n, "", null, undefined, and NaN."_

https://developer.mozilla.org/en-US/docs/Glossary/Truthy

File: src/views/SelectJobsModal.vue [hunk 4]
```diff
@@ -10,9 +10,13 @@
...
   <ion-content>
-    <ion-searchbar v-model="queryString" :placeholder="$t('Search jobs')" @keyup.enter="search($event)" />
+    <ion-searchbar :placeholder="$t('Search jobs')" @keyup.enter="search($event)" />
 
-    <div v-if="jobs.length === 0" class="ion-text-center">
+    <div v-if="queryString.length === 0" class="ion-text-center">
+      <p>{{ $t("Searched jobs will appear here") }}</p>
+    </div>    
+
+    <div v-else-if="jobs.length === 0 && queryString.length != 0" class="ion-text-center">
```
Comment (adityasharma7) [inline src/views/SelectJobsModal.vue:19]: I think the condition `queryString.length != 0"` might not be needed, else-if will execute only when `queryString.length === 0` fails.

**Review by adityasharma7 — CHANGES_REQUESTED** [review]

File: src/views/SelectJobsModal.vue (hunk 3 above)
Comment (k2maan) [reply src/views/SelectJobsModal.vue]: Yes, sir. The empty queryString itself is a false value.

File: src/views/SelectJobsModal.vue (hunk 4 above)
Comment (k2maan) [reply src/views/SelectJobsModal.vue]: Improved.
