### PR TITLE
Fixed: 'now' option for run time not working (#517)

### LINKED ISSUE #517: While updating a job, selecting 'Now' for the runtime does not work
## Current behavior
While updating a job, selecting 'now' for the runtime does not work as it does not send any time in the payload.

## Expected behavior
When we select now, the job should instantly run and update. Now function in the runtime should work as expected.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by k2maan**
### Related Issues

Closes #517 

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

### CODE REVIEW

File: src/components/InitialJobConfiguration.vue [hunk 1]
```diff
@@ -216,7 +216,7 @@ export default defineComponent({
 
       // Handling the case for 'Now'. Sending the now value will fail the API as by the time
       // the job is ran, the given 'now' time would have passed. Hence, passing empty 'run time'
-      !isCustomRunTime(this.runTime) && this.runTime == 0 ? job.runTime = '' : job.runTime += DateTime.now().toMillis()
+      !isCustomRunTime(this.runTime) ? job.runTime = DateTime.now().toMillis() + this.runTime : job.runTime = this.runTime
```
Comment (adityasharma7) [inline src/components/InitialJobConfiguration.vue:219]:
```suggestion
      job.runTime = !isCustomRunTime(this.runTime) ? DateTime.now().toMillis() + this.runTime : this.runTime
```

**Review by adityasharma7 — CHANGES_REQUESTED** [review]

**Review by adityasharma7 — APPROVED** [review]
