### PR TITLE
Fixed: Jobs getting scheduled multiple times(#32qywdd)

### LINKED ISSUE #311: Static jobs should be scheduled once
## Current behavior

Navigate to any page, order, inventory etc where the job is disabled. Try scheduling the job from job configuration section/page, after the success message, again click on save changes it will schedule another instance of the job.

## Expected behavior

Users should be allowed to schedule it once only. Save changes should be disabled till current action is not completed and once done job scheduled should be updated through it

### PR DESCRIPTION
**Pull request by shashwatbangar**
### Related Issues

Closes #311 

### Short Description and Why It's Useful

Earlier, when we navigate to any page, order, inventory etc where the job is disabled & try scheduling the job from job configuration section/page, after the success message, again click on save changes it will schedule another instance of the job. 

Reason being when we click on SAVE CHANGES again, the currentJob is not yet updated or more specifically, marked as scheduled. This was because after hitting the scheduleJob API, response was not handled correctly and set in currentJob state.

As a result when we click on SAVE CHANGES, currentJob shows that job is still in DRAFT state hence will get scheduled again whereas what should happen is, when we schedule a job for the first time, it should get updated and marked as PENDING. So when we update this job or disable it, job will get updated not get scheduled again.

### Screenshots of Visual Changes before/after (If There Are Any)

https://user-images.githubusercontent.com/62360781/208084725-7b56d6a5-c337-4036-9729-0dd4bae68905.mov

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

### CODE REVIEW

File: src/store/modules/job/actions.ts [hunk 1]
```diff
@@ -458,19 +458,17 @@ const actions: ActionTree<JobState, RootState> = {
...
+        const jobs = await dispatch('fetchJobs', {
           inputFields: {
             'systemJobEnumId': payload.systemJobEnumId,
             'systemJobEnumId_op': 'equals'
           }
         })
-        if(jobs.status === 200 && !hasError(jobs) && jobs.data?.docs.length) {
-          jobs = jobs.data?.docs;
-          const job = jobs.find((job: any) => job?.jobId === payload.jobId);
+        const job = jobs[1];
```
Comment (ymaheshwari1) [inline src/store/modules/job/actions.ts:467]: Why we are accessing values using index? As there is no gurantee that the specific job will come on that index only.

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]

File: src/store/modules/job/actions.ts (hunk 1 above)
Comment (shashwatbangar) [reply src/store/modules/job/actions.ts]: Right sir. Fixed it.

File: src/store/modules/job/actions.ts [hunk 2]
```diff
@@ -458,19 +458,17 @@ const actions: ActionTree<JobState, RootState> = {
...
           inputFields: {
             'systemJobEnumId': payload.systemJobEnumId,
             'systemJobEnumId_op': 'equals'
           }
         })
-        if(jobs.status === 200 && !hasError(jobs) && jobs.data?.docs.length) {
-          jobs = jobs.data?.docs;
-          const job = jobs.find((job: any) => job?.jobId === payload.jobId);
+        const job = jobs.find((job: any) => job?.jobId === payload.jobId);
+        if(job.status === 200 && !hasError(job) && job.data?.docs.length) {
```
Comment (adityasharma7) [inline src/store/modules/job/actions.ts:468]: Improve variable name job, status, data etc are attributes of response not job

**Review by adityasharma7 — CHANGES_REQUESTED** [review]
