### PR TITLE
Fixed: Jobs repeatation in moreJobs sections on all pages(#2vjxdha)

### LINKED ISSUE #257: Implement more jobs section on all pages
Implement more jobs section on all pages
Jobs will be fetched based upon job enum type id

### PR DESCRIPTION
**Pull request by shashwatbangar**
### Related Issues

Closes #257 

### Short Description and Why It's Useful

We have hardcoded jobs at the top of pages & below we have moreJobs section, earlier hardCoded jobs were are shown in moreJobs section which is wrong. This happened because enumTypeId were same for both. Now fixed it. 

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

### CODE REVIEW

File: src/views/Product.vue [hunk 1]
```diff
@@ -40,7 +40,7 @@
               <ion-toggle slot="end" :checked="deleteProductsWebhook" @ionChange="updateWebhook($event['detail'].checked, 'DELETE_PRODUCTS')" color="secondary" />
             </ion-item>
           </ion-card>
-          <MoreJobs v-if="moreJobs.length" :jobs="moreJobs" :jobEnums="jobEnums" />
+          <MoreJobs v-if="getMoreJobs(jobEnums, 'PRODUCT_SYS_JOB').length" :jobs="getMoreJobs(jobEnums, 'PRODUCT_SYS_JOB').length" :jobEnums="jobEnums" />
```
Comment (ymaheshwari1) [inline src/views/Product.vue:43]: Define a local property to declare the enumTypeId value.

File: src/views/Orders.vue [hunk 2]
```diff
@@ -500,7 +495,7 @@ export default defineComponent({
     if (this.currentEComStore.productStoreId) {
       this.getAutoCancelDays();
     }
-    this.fetchMoreJobs();
+    // this.moreJobs = this.getMoreJobs(this.jobEnums, "ORDER_SYS_JOB");
```
Comment (ymaheshwari1) [inline src/views/Orders.vue:498]: Remove this comment if not needed.

File: src/store/modules/job/getters.ts [hunk 3]
```diff
@@ -57,17 +57,15 @@ const getters: GetterTree <JobState, RootState> = {
...
-      jobs = state.more.pending.list.reduce((jobs: any, pendingJob: any) => {
-        jobs[pendingJob.systemJobEnumId] = pendingJob;
-        return jobs;
-      }, jobs)
+    getMoreJobs: (state) => (jobEnums: any, enumTypeId: string): any => {
+      const orderJobEnumIds = Object.values(jobEnums) as any;
 
-      return Object.values(jobs)
+      return Object.keys(state.cached).reduce((orders: any, enumId: any) => {
+        if(orderJobEnumIds.indexOf(enumId) === -1 && state.cached[enumId]?.enumTypeId === enumTypeId) {
```
Comment (ymaheshwari1) [inline src/store/modules/job/getters.ts:64]: Instead in place of indexOf, I think using includes will be a good option.

File: src/store/modules/job/getters.ts [hunk 4]
```diff
@@ -57,17 +57,15 @@ const getters: GetterTree <JobState, RootState> = {
...
+          orders.push(state.cached[enumId])
```
Comment (ymaheshwari1) [inline src/store/modules/job/getters.ts:65]: I think we should change `order` specific variable name, the same getter is being used on all pages.

File: src/store/modules/job/getters.ts [hunk 5]
```diff
@@ -57,17 +57,15 @@ const getters: GetterTree <JobState, RootState> = {
...
-      }, {})
-      jobs = state.more.pending.list.reduce((jobs: any, pendingJob: any) => {
-        jobs[pendingJob.systemJobEnumId] = pendingJob;
-        return jobs;
-      }, jobs)
+    getMoreJobs: (state) => (jobEnums: any, enumTypeId: string): any => {
+      const orderJobEnumIds = Object.values(jobEnums) as any;
 
-      return Object.values(jobs)
+      return Object.keys(state.cached).reduce((orders: any, enumId: any) => {
```
Comment (ymaheshwari1) [inline src/store/modules/job/getters.ts:63]:
```suggestion
      return Object.keys(state.cached).reduce((orders: any, enumId: string) => {
```

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]

File: src/views/Orders.vue (hunk 2 above)
Comment (shashwatbangar) [reply src/views/Orders.vue:498]: Done sir

File: src/store/modules/job/getters.ts (hunk 3 above)
Comment (shashwatbangar) [reply src/store/modules/job/getters.ts:64]: Sure sir

File: src/store/modules/job/getters.ts (hunk 4 above)
Comment (shashwatbangar) [reply src/store/modules/job/getters.ts:65]: Right sir. Fixed it.

File: src/store/modules/job/getters.ts (hunk 5 above)
Comment (shashwatbangar) [reply src/store/modules/job/getters.ts:63]: done

File: src/views/Product.vue (hunk 1 above)
Comment (shashwatbangar) [reply src/views/Product.vue:43]: Done sir

File: src/store/modules/job/getters.ts [hunk 6]
```diff
@@ -57,17 +57,15 @@ const getters: GetterTree <JobState, RootState> = {
...
-      jobs = state.more.pending.list.reduce((jobs: any, pendingJob: any) => {
-        jobs[pendingJob.systemJobEnumId] = pendingJob;
-        return jobs;
-      }, jobs)
+    getMoreJobs: (state) => (jobEnums: any, enumTypeId: string): any => {
+      const orderJobEnumIds = Object.values(jobEnums) as any;
 
-      return Object.values(jobs)
+      return Object.keys(state.cached).reduce((jobs: any, enumId: string) => {
+        if(!orderJobEnumIds.includes(enumId) && state.cached[enumId]?.enumTypeId === enumTypeId) {
```
Comment (adityasharma7) [inline src/store/modules/job/getters.ts:64]: We should first check enumTypeId as it will have many other types of jobs and it is better to avoid includes operation for other types
```suggestion
        if(state.cached[enumId]?.enumTypeId === enumTypeId && !orderJobEnumIds.includes(enumId)) {
```

File: src/views/Inventory.vue [hunk 7]
```diff
@@ -171,22 +172,16 @@ export default defineComponent({
         this.getTemporalExpr(this.getJobStatus(this.jobEnums[enumId]))?.description :
         this.$t('Disabled')
     },
-    async fetchMoreJobs() {
-      await this.store.dispatch("job/fetchMoreJobs", {
-        "inputFields":{
-          "enumTypeId": "INVENTORY_SYS_JOB",
-        },
-      });
+    getMoreJobs(jobEnums: any, enumTypeId: string) {
```
Comment (adityasharma7) [inline src/views/Inventory.vue:175]: Why this is needed? we could directly use moreJobs(jobEnums, enumTypeId)

File: src/store/modules/job/actions.ts [hunk 8]
```diff
@@ -357,7 +357,7 @@ const actions: ActionTree<JobState, RootState> = {
         ...payload.inputFields
       },
       "noConditionFind": "Y",
-      "viewSize": (payload.inputFields?.systemJobEnumId?.length * 3)
+      "viewSize": (payload.inputFields?.systemJobEnumId?.length * 3) || 30
```
Comment (adityasharma7) [inline src/store/modules/job/actions.ts:360]: We should increase this value

**Review by adityasharma7 — CHANGES_REQUESTED** [review]

File: src/store/modules/job/getters.ts (hunk 6 above)
Comment (shashwatbangar) [reply src/store/modules/job/getters.ts:64]: Done sir

File: src/views/Inventory.vue (hunk 7 above)
Comment (shashwatbangar) [reply src/views/Inventory.vue:175]: Yes sir. Fixed it.

**Review by adityasharma7 — APPROVED** [review]
